"""
castle/ui/cluster_tree.py
Tree view rendering for cluster hierarchy.

Cluster names use '_' as the hierarchy delimiter, generated by
auto_generate_cluster_name() in castle/core/cluster.py:
    init → init_a0, init_a1
    init_a0 → init_a0_b0, init_a0_b1
    init_a0_b0 → init_a0_b0_c0, ...

Parent nodes (e.g. 'init_a0') are NOT stored in cluster_meta once they
have been split — they exist only as name prefixes of their children.
This module synthesises them for display and computes cumulative counts.
"""

from collections import Counter
from typing import Dict, Optional


def _infer_all_nodes(real_names: set) -> set:
    """Expand a set of real cluster names to include all ancestor prefixes.

    A prefix is a parent node if at least one real cluster name starts
    with ``prefix + '_'``.  This covers arbitrary nesting depth without
    assuming a fixed separator letter pattern.

    Args:
        real_names: set of cluster name strings present in cluster_meta.

    Returns:
        Extended set containing real names + all synthetic parent prefixes.
    """
    parents: set = set()
    for name in real_names:
        parts = name.split('_')
        for i in range(1, len(parts)):
            prefix = '_'.join(parts[:i])
            # Only a valid parent if some real cluster lives under it
            if any(n.startswith(prefix + '_') for n in real_names):
                parents.add(prefix)
    return real_names | parents


def _immediate_parent(name: str, all_nodes: set) -> Optional[str]:
    """Return the longest strict prefix of ``name`` that is in ``all_nodes``."""
    parts = name.split('_')
    for i in range(len(parts) - 1, 0, -1):
        prefix = '_'.join(parts[:i])
        if prefix in all_nodes:
            return prefix
    return None


def _build_tree(cluster_meta: dict, cluster_array) -> Dict[str, dict]:
    """Build a complete tree dict including synthetic parent nodes.

    Args:
        cluster_meta: {id: {name, color, ...}}
        cluster_array: numpy array of per-frame cluster assignments.

    Returns:
        dict {name: {depth, cumulative, is_real, meta, cid}}
        Sorted by name (preserves hierarchical ordering).
    """
    direct = Counter(cluster_array.tolist())
    name_to_cid = {meta['name']: cid for cid, meta in cluster_meta.items()}
    real_names = set(name_to_cid.keys())

    all_nodes = _infer_all_nodes(real_names)

    # Cumulative count: start with direct counts for real nodes
    cum: Dict[str, int] = {
        n: (direct.get(name_to_cid[n], 0) if n in real_names else 0)
        for n in all_nodes
    }

    # Depth via parent chain
    parent_map = {n: _immediate_parent(n, all_nodes) for n in all_nodes}

    def depth_of(name: str) -> int:
        d, n = 0, name
        while parent_map.get(n) is not None:
            d += 1
            n = parent_map[n]
        return d

    depth_map = {n: depth_of(n) for n in all_nodes}

    # Bottom-up accumulation: deepest nodes first
    for name in sorted(all_nodes, key=lambda n: -depth_map[n]):
        parent = parent_map.get(name)
        if parent is not None:
            cum[parent] = cum.get(parent, 0) + cum.get(name, 0)

    result = {}
    for name in sorted(all_nodes):
        cid = name_to_cid.get(name)
        meta = cluster_meta.get(cid) if cid is not None else None
        # A node is a "container" if it has children in all_nodes
        is_container = any(
            parent_map.get(other) == name for other in all_nodes if other != name
        )
        result[name] = {
            'depth': depth_map[name],
            'cumulative': cum.get(name, 0),
            'is_real': name in real_names,
            'is_container': is_container,
            'meta': meta,
            'cid': cid,
        }
    return result


def build_cluster_tree_markdown(cluster_meta, cluster_array):
    """Build a markdown tree from cluster metadata.

    Parent nodes are synthesised from name prefixes and shown with their
    cumulative (subtree) frame count.

    Args:
        cluster_meta: dict {id: {name, color}}
        cluster_array: numpy array of cluster assignments

    Returns:
        Markdown string with tree visualization
    """
    tree = _build_tree(cluster_meta, cluster_array)
    lines = []
    for name, info in tree.items():
        if info['cumulative'] == 0:
            continue
        depth = info['depth']
        indent = '    ' * depth
        prefix = '├── ' if depth > 0 else ''
        line = f"{indent}{prefix}🔸 **{name}** ({info['cumulative']} bins)"
        lines.append(line)

    if not lines:
        return "*No clusters yet*"
    return "### 📊 Cluster Tree\n\n" + "\n\n".join(lines)


_TREE_CSS = """\
<style>
.castle-cluster-tree{font-family:"Courier New",Consolas,monospace;font-size:12.5px;
  border:1px solid var(--border-color-primary,#e0e0e0);border-radius:6px;padding:4px;max-height:460px;
  overflow-y:auto;background:var(--background-fill-primary,#fcfcfc);margin-bottom:2px;}
.cct-node{display:flex;align-items:center;padding:3px 6px;border-radius:4px;
  gap:5px;line-height:1.6;cursor:pointer;user-select:none;color:var(--body-text-color,#333);
  transition:background 0.1s;}
.cct-node:hover{background:color-mix(in srgb,var(--color-accent,#1a73e8) 10%,transparent);}
.cct-node.cct-selected{background:color-mix(in srgb,var(--color-accent,#1a73e8) 18%,transparent);
  font-weight:600;border-left:3px solid var(--color-accent,#1a73e8);padding-left:3px;}
.cct-icon{flex-shrink:0;}
.cct-name{flex:1;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}
.cct-count{flex-shrink:0;font-size:10.5px;color:var(--body-text-color-subdued,#666);
  background:var(--background-fill-secondary,#eee);
  padding:0 4px;border-radius:8px;white-space:nowrap;}
</style>"""


def build_cluster_tree_html(cluster_meta: dict, cluster_array) -> str:
    """Build an HTML visual tree of the cluster hierarchy (display-only).

    Uses CSS ``padding-left`` for indentation — reliable across all browsers
    and unaffected by HTML whitespace collapsing.

    Args:
        cluster_meta: dict {id: {name, color, ...}}
        cluster_array: numpy array of per-frame cluster assignments.

    Returns:
        HTML string for ``gr.HTML`` component.
    """
    tree = _build_tree(cluster_meta, cluster_array)

    rows = []
    for name, info in tree.items():
        if info['cumulative'] == 0:
            continue
        depth = info['depth']
        indent_px = 8 + depth * 20

        if info['is_container']:
            icon = '📂'
        else:
            color = (info['meta'] or {}).get('color', 'grey')
            icon = '🟢' if color != 'grey' else '📁'

        safe_name = name.replace("'", "\\'")
        rows.append(
            f'<div class="cct-node" style="padding-left:{indent_px}px"'
            f' onclick="castleTreeClick(this,\'{safe_name}\')"'
            f' data-name="{name}">'
            f'<span class="cct-icon">{icon}</span>'
            f'<span class="cct-name">{name}</span>'
            f'<span class="cct-count">{info["cumulative"]}</span>'
            f'</div>'
        )

    if not rows:
        return (
            f'{_TREE_CSS}'
            '<div class="castle-cluster-tree">'
            '<span style="color:#888;font-style:italic;padding:6px;display:block">'
            'No clusters yet — run DBSCAN to create clusters.'
            '</span></div>'
        )

    return (
        f'{_TREE_CSS}'
        '<div class="castle-cluster-tree">\n'
        + '\n'.join(rows)
        + '\n</div>'
    )


def build_cluster_tree_choices(cluster_meta, cluster_array):
    """Build tree-formatted choices for gr.Radio.

    Returns list of (display_label, value) where:
    - display_label has indentation + branch chars + frame count
    - value is the cluster name (used for selection)

    Parent/container nodes are included; selecting them will drill into
    the full subtree (handled by latent_explorer.select with prefix matching).

    Args:
        cluster_meta: dict {id: {name, color}}
        cluster_array: numpy array of cluster assignments

    Returns:
        List of (label, value) tuples for gr.Radio choices
    """
    tree = _build_tree(cluster_meta, cluster_array)
    choices = []
    for name, info in tree.items():
        if info['cumulative'] == 0:
            continue
        depth = info['depth']
        # Use non-breaking spaces so HTML does not collapse the indentation.
        # 4 NBSP per depth level gives clear visual separation in gr.Radio.
        nbsp = ' '
        indent = nbsp * 4 * depth
        prefix = f'├──{nbsp}' if depth > 0 else ''

        if info['is_container']:
            icon = '📂'
        else:
            color = (info['meta'] or {}).get('color', 'grey')
            icon = '🟢' if color != 'grey' else '📁'

        display_label = f"{indent}{prefix}{icon}{nbsp}{name} ({info['cumulative']} frames)"
        choices.append((display_label, name))

    return choices
